### ISSUE TITLE
function deprecated with moodle 2.8.8

### ISSUE THREAD

**Issue by sumanbogati** [vidyamantra/moodle-mod_congrea#1]
The following error message is coming when we are trying to create the virtualclass activity with "debugging mode on" in moodle 2.8 

`mod_virtualclass_mod_form::standard_intro_elements() in /var/www/vhosts/growdly.com/httpdocs/mod/virtualclass/mod_form.php* on  71`

**Comment by pinky28** [comment]
Problem has been fixed in vesion 2.0
