### ISSUE TITLE
Legacy setting storage used

### ISSUE THREAD

**Issue by mudrd8mz** [vidyamantra/moodle-mod_congrea#3]
https://docs.moodle.org/dev/Plugin_contribution_checklist#Settings-storage

The current setting `congrea_serve` should better be named `mod_congrea/serve` which will make it to be stored in the config_plugins table. You will want to change places where you access it via `$CFG` then.

**Comment by jgupta** [comment]
Thanks for pointing it out. Can you also send a reference to any plugin/code/example?
