### ISSUE TITLE
Quizzes hidden on moodle are visible on Congrea

### ISSUE THREAD

**Issue by Sudhanshu0044** [vidyamantra/moodle-mod_congrea#41]
Quiz should not be visible on congrea which are hidden on moodle.
Screenshots are attached.
![screenshot from 2018-06-09 16-05-11](https://user-images.githubusercontent.com/38027574/41190567-02a97f3e-6bff-11e8-9561-9d4ea49e3585.png)
![screenshot from 2018-06-09 16-05-23](https://user-images.githubusercontent.com/38027574/41190568-02d2256a-6bff-11e8-9ba2-983a4d5213c9.png)

**Comment by ravi18011991** [comment]
solve
