### ISSUE TITLE
Upload file page: cancel button doesn't redirects to previous page.

### ISSUE THREAD

**Issue by ypshukla** [vidyamantra/moodle-mod_congrea#51]
When choose cancel on upload files page, it still remains on the same page. It should redirect to previous page.

![screenshot from 2018-07-12 16-30-37](https://user-images.githubusercontent.com/36185596/42629448-ee0c1a1c-85f0-11e8-8d08-eaa892695353.png)

**Comment by ravi18011991** [comment]
solve
