### ISSUE TITLE
Issue in backup & restoration

### ISSUE THREAD

**Issue by Sudhanshu0044** [vidyamantra/moodle-mod_congrea#53]
After restoring the course or activity the session also get restored but the first file of session replaces all the sessions without changing the name of the file name,time created.
![screenshot from 2018-07-13 15-13-25](https://user-images.githubusercontent.com/38027574/42685092-b6218e6a-86af-11e8-9fd0-c363def23819.png)

**Comment by ravi18011991** [comment]
solve
